apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "wordpress-role"
        vault.hashicorp.com/agent-inject-secret-wordpress-db.env: "secret/data/wordpress-db"
        vault.hashicorp.com/agent-requests-cpu: "25m"
        vault.hashicorp.com/agent-limits-cpu: "100m"
        vault.hashicorp.com/agent-requests-mem: "32Mi"
        vault.hashicorp.com/agent-limits-mem: "128Mi"
        vault.hashicorp.com/agent-inject-template-wordpress-db.env: |
          {{- with secret "secret/data/wordpress-db" -}}
          export WORDPRESS_DB_HOST="{{ .Data.data.host }}"
          export WORDPRESS_DB_NAME="{{ .Data.data.mysql_database }}"
          export WORDPRESS_DB_USER="{{ .Data.data.mysql_user }}"
          export WORDPRESS_DB_PASSWORD="{{ .Data.data.mysql_password }}"
          {{- end }}
    spec:
      serviceAccountName: wordpress
      containers:
        - name: wordpress
          image: wordpress:6.6-apache
          command:
            - sh
            - -c
          args:
            - . /vault/secrets/wordpress-db.env && docker-entrypoint.sh apache2-foreground
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
            - name: tb-events-plugin
              mountPath: /var/www/html/wp-content/plugins/tb-events/tb-events.php
              subPath: tb-events.php
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: tb-events-plugin
          configMap:
            name: tb-events-plugin

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80