containers:
  - name: mariadb
    image: mariadb:11

    ports:
      - containerPort: 3306

    envFrom:
      - secretRef:
          name: wordpress-mariadb-secret

    volumeMounts:
      - name: mariadb-storage
        mountPath: /var/lib/mysql

    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"

      limits:
        memory: "512Mi"
        cpu: "500m"