apiVersion: apps/v1
kind: Deployment
metadata:
  name: thingsboard
  namespace: thingsboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thingsboard
  template:
    metadata:
      labels:
        app: thingsboard
    spec:
      containers:
        - name: thingsboard
          image: thingsboard/tb-postgres:3.8.1
          ports:
            - containerPort: 9090
            - containerPort: 1883
            - containerPort: 7070
          env:
            - name: TB_QUEUE_TYPE
              value: in-memory
            - name: SECURITY_BASIC_ENABLED
              value: "true"
            - name: SECURITY_OAUTH2_ENABLED
              value: "false"
          volumeMounts:
            - name: thingsboard-storage
              mountPath: /data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
      volumes:
        - name: thingsboard-storage
          persistentVolumeClaim:
            claimName: thingsboard-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: thingsboard
  namespace: thingsboard
spec:
  selector:
    app: thingsboard
  ports:
    - name: http
      port: 9090
      targetPort: 9090
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: edge
      port: 7070
      targetPort: 7070