apiVersion: v1
kind: Secret
metadata:
  name: thingsboard-postgres-secret
  namespace: thingsboard
type: Opaque
stringData:
  POSTGRES_DB: thingsboard
  POSTGRES_USER: thingsboard
  POSTGRES_PASSWORD: thingsboard123