apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thingsboard-postgres-pvc
  namespace: thingsboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi