apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: grafana
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ais25131/cloud-native-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/apps/grafana/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true