apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ais25131/cloud-platforms.git
    targetRevision: main
    path: kubernetes/apps/kube-state-metrics/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-state-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
