apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-topology-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ais25131/cloud-platforms.git
    targetRevision: main
    path: kubernetes/apps/rabbitmq-topology-operator/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true