apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thingsboard
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ais25131/cloud-native-infrastructure.git
    targetRevision: main
    path: kubernetes/apps/thingsboard/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: thingsboard

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true