apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - enabled-plugins-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - rabbitmq-setup-job.yaml
  - serviceaccount.yaml