apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-setup
  namespace: rabbitmq
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: rabbitmq:3.13-management
          command:
            - /bin/sh
            - -c
            - |
              sleep 20

              rabbitmqadmin \
                --host=rabbitmq.rabbitmq.svc.cluster.local \
                --port=15672 \
                --username="$RABBITMQ_USER" \
                --password="$RABBITMQ_PASSWORD" \
                declare queue name=orders durable=false auto_delete=false
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS