apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-setup
  namespace: rabbitmq
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: "rabbitmq-role"
        vault.hashicorp.com/agent-inject-secret-rabbitmq.env: "secret/data/rabbitmq"
        vault.hashicorp.com/agent-inject-template-rabbitmq.env: |
          {{- with secret "secret/data/rabbitmq" -}}
          export RABBITMQ_USER="{{ .Data.data.rabbitmq_user }}"
          export RABBITMQ_PASSWORD="{{ .Data.data.rabbitmq_password }}"
          {{- end }}
    spec:
      serviceAccountName: rabbitmq
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: rabbitmq:3.13-management
          command:
            - /bin/sh
            - -c
            - |
              . /vault/secrets/rabbitmq.env

              sleep 20

              rabbitmqadmin \
                --host=rabbitmq.rabbitmq.svc.cluster.local \
                --port=15672 \
                --username="$RABBITMQ_USER" \
                --password="$RABBITMQ_PASSWORD" \
                declare queue name=events durable=false auto_delete=false