apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-red-local-to-kourier
  namespace: kourier-system
spec:
  ingressClassName: traefik
  rules:
    - host: node-red.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kourier
                port:
                  number: 80