apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: node-red-flows
    namespace: node-red
    files:
      - flows.json=../../../integrations/node-red/flows-new/json

generatorOptions:
  disableNameSuffixHash: true