Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"


  config.vm.define "jenkins" do |vm|

    vm.vm.hostname = "jenkins"

    vm.vm.network "private_network", ip: "192.168.56.22"

    vm.vm.provider "virtualbox" do |vb|
      vb.name   = "jenkins"
      vb.memory = 2048
      vb.cpus   = 2
    end

  end


  config.vm.define "k8s" do |vm|

    vm.vm.hostname = "k8s"

    vm.vm.network "private_network", ip: "192.168.56.21"

    vm.vm.provider "virtualbox" do |vb|
      vb.name   = "k8s"
      vb.memory = 8192
      vb.cpus   = 6
    end

  end


end