apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-api

  template:
    metadata:
      labels:
        app: order-api

    spec:
      containers:
        - name: order-api

          image: ais25131/order-api:v2

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: APP_VERSION
              value: "v1"

            - name: RABBITMQ_HOST
              value: "rabbitmq.rabbitmq.svc.cluster.local"

            - name: RABBITMQ_USER
              value: "user"

            - name: RABBITMQ_PASSWORD
              value: "password"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000