apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-api
  namespace: order-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-api

  template:
    metadata:
      labels:
        app: order-api

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "vault-role"
        vault.hashicorp.com/agent-inject-secret-rabbitmq: "secret/data/rabbitmq"
        vault.hashicorp.com/agent-inject-template-rabbitmq: |
          {{- with secret "secret/data/rabbitmq" -}}
          RABBITMQ_HOST={{ .Data.data.host }}
          RABBITMQ_USER={{ .Data.data.username }}
          RABBITMQ_PASSWORD={{ .Data.data.password }}
          RABBITMQ_PORT={{ .Data.data.port }}
          RABBITMQ_QUEUE={{ .Data.data.queue }}
          {{- end }}

    spec:
      serviceAccountName: vault-serviceaccount

      containers:
        - name: order-api

          image: docker.io/ais25131/order-api:4
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: APP_VERSION
              value: "4"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"