apiVersion: serving.knative.dev/v1
kind: Service

metadata:
  name: order-api-knative
  namespace: order-api

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "3"

        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "vault-role"
        vault.hashicorp.com/agent-inject-secret-rabbitmq: "secret/data/rabbitmq"
        vault.hashicorp.com/agent-inject-template-rabbitmq: |
          {{- with secret "secret/data/rabbitmq" -}}
          RABBITMQ_USER={{ .Data.data.rabbitmq_user }}
          RABBITMQ_PASSWORD={{ .Data.data.rabbitmq_password }}
          {{- end }}

    spec:
      serviceAccountName: vault-serviceaccount

      containers:
        - image: docker.io/ais25131/order-api:29
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: APP_VERSION
              value: "29-events-through-order-api"

            - name: PUSHGATEWAY_URL
              value: "pushgateway.monitoring.svc.cluster.local:9091"

            - name: RABBITMQ_HOST
              value: "rabbitmq.rabbitmq.svc.cluster.local"

            - name: RABBITMQ_PORT
              value: "5672"

            - name: RABBITMQ_QUEUE
              value: "events"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"