apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'pushgateway'
        static_configs:
          - targets:
              - pushgateway.monitoring.svc.cluster.local:9091

      - job_name: 'order-api'
        metrics_path: /metrics
        static_configs:
          - targets:
              - order-api-knative.order-api.svc.cluster.local:80

      - job_name: 'rabbitmq'
        metrics_path: /metrics
        static_configs:
          - targets:
              - rabbitmq.rabbitmq.svc.cluster.local:15692